"""empty message

Revision ID: 888b38ae3411
Revises: 
Create Date: 2018-10-18 20:44:45.636896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888b38ae3411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('age', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('age'),
    sa.UniqueConstraint('name')
    )
    op.create_unique_constraint(None, 'accounts', ['email'])
    op.create_unique_constraint(None, 'accounts', ['fullname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_table('customer')
    # ### end Alembic commands ###
