"""empty message

Revision ID: f1ed560d8451
Revises: 
Create Date: 2018-09-30 00:26:06.824582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ed560d8451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=128), nullable=True),
    sa.Column('Password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('staff',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=128), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Salary', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('Work', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('account')
    # ### end Alembic commands ###
